### ISSUE TITLE
How to profile the DL training and inference

### ISSUE THREAD

**Issue by falcon-xu** [NVlabs/FasterViT#110]
Hello, it's a wonderful work.

I'm interested in FasterViT profiling in Appendix H. I knew that the NVIDIA DLSIM was the internal tool. 
Could you please introduce some open-source tools to profile latency, FLOPs, memory?
I always want to find a similar profiling tool.  

Thanks a lot.

**Comment by ahatamiz** [comment]
Hi @lostsword , thanks for your interest in our work. My suggestion would be to use `ptflops`. 

As a simple example on how to measure the model complexity:


```
from ptflops import get_model_complexity_info

model = faster_vit_0_224()
model.eval()
macs, params = get_model_complexity_info(model, tuple([3, 224, 224]),
                                             as_strings=False, print_per_layer_stat=False, verbose=False)
```

I hope this is useful ! 

Regards,
