### ISSUE TITLE
Use FasterViT model like a backbone for segmentation model

### ISSUE THREAD

**Issue by heorhiikalaichev** [NVlabs/FasterViT#114]
Hi!

First of all, thank you for your perfect work.

I'm working on training a segmentation model in the mmseg pipeline and I'm wondering about:
1. Which model is more suitable for the segmentation task classic fastervit or faster_vit_any_res?
2. Are you going to create models for segmentation?

Thank you in advance!

**Comment by ahatamiz** [comment]
Thanks @heorhiikalaichev  for the comment. Both models are suitable for segmentation, however in the case of faster_vit_any_res, you should be careful of not introducing new carrier tokens if we want to use a pre-trained checkpoint. This is largely controlled by [hat flag](https://github.com/NVlabs/FasterViT/blob/main/fastervit/models/faster_vit_any_res.py#L1092) which overrides other conditions for creating hat based on feature_size vs window size. 

We will create and publish the models for downstream tasks soon.
