### ISSUE TITLE
Inquiry for detection codes

### ISSUE THREAD

**Issue by George0726** [NVlabs/FasterViT#119]
Hi author,

Thanks for your impressive work!  May I ask if you have plans to release your Segmentation/ Detection codes and checkpoints?

**Comment by ahatamiz** [comment]
Hi @George0726 

Thanks for your interest regarding our work and inquiry about object detection.

 We have released the FasterViT object detection repository with DINO [here](https://github.com/NVlabs/FasterViT/tree/main/object_detection). 

We will add pretrained checkpoints very soon. But in the meantime, please check the [FasterViT backbone](https://github.com/NVlabs/FasterViT/blob/main/object_detection/models/dino/fastervit.py) as it contains the required changes for object detection. 

I hope you find this useful !
