### ISSUE TITLE
Training FasterViT on VisDrone2019 dataset

### ISSUE THREAD

**Issue by bshakya77** [NVlabs/FasterViT#125]
Hello,

I am trying to train FasterViT model on VisDrone2019 dataset for small object detection. Is there any resources that can guide me on this task. Is it possible to train FasterViT model to train on VisDrone2019 dataset? Does it provide any API or python code to train FasterViT model?

Any help is appreciated.

**Comment by ahatamiz** [comment]
We have published motrv2+FasterViT code/models for object tracking. Please check [here](https://github.com/NVlabs/FasterViT/tree/main/downstream/object_tracking/motrv2).
