### ISSUE TITLE
HAT

### ISSUE THREAD

**Issue by YSLDTZY** [NVlabs/FasterViT#126]
Hello author, the work you have done is very good, I hope I can use HAT in other places, I don't know how to modify the medicine, I hope the author can teach me, thank you, I look forward to your early reply.

**Comment by ahatamiz** [comment]
HAT is designed for taking into account the cross-regions dependencies when computing self-attention. For your application of interest, we recommend checking HAT and any_resolution HAT which allows the extension of HAT for arbitrary resolutions.
