### ISSUE TITLE
Latency under bs=1 seems not impressive like throughput under bs=128.

### ISSUE THREAD

**Issue by TsingWei** [NVlabs/FasterViT#129]

**Comment by tmanh** [comment]
I also observe the same thing, SwinV2 is faster than FasterViT when the batch size is small (1-6 images). But, when the batch size become larger FasterVit is much faster than SwinV2 (>= 10 images).

**Comment by ahatamiz** [comment]
Our model has been designed for bs=128. However, in the updated arxiv [manuscript](https://arxiv.org/abs/2306.06189), we have provided more comparisons for different hardware.
