### ISSUE TITLE
ImageNet-21K checkpoint without fine-tuning!

### ISSUE THREAD

**Issue by black0017** [NVlabs/FasterViT#137]
Congrats on the acceptance and great work!

Any chance you could provide an ImageNet-21K faster-vit checkpoint **without** ImageNet-1K fine-tuning.

I would be very interested to see how the ImageNet-21K-based learned features can be used for downstream tasks.

Thanks a lot and have a nice day!

N.A.

**Comment by ahatamiz** [comment]
Hi @black0017 

Thank you ! we have provided the raw pre-trained ImageNet-21K model weights for FasterViT-4 in this [link](https://drive.google.com/file/d/1T3jDrzlTmTcZVS1Dh01Fl3J2LXZHWKdL/view?usp=sharing).

Kind Regards,

**Comment by black0017** [comment]
Amazing, thank you much for providing the weights! It's so hard to find pre-trained models on  ImageNet-21K!!!! Have a fab day!!!
