### ISSUE TITLE
Why use CNN in the first two stage.

### ISSUE THREAD

**Issue by jamesben6688** [NVlabs/FasterViT#138]
I noticed that you used cnn in the first two stages. Have you tried using HAT Block in the first two stages?

**Comment by ahatamiz** [comment]
HAT block has been designed for Transformer layers, as an efficient and scalable way for computing self-attention and taking into account the cross-region dependencies. For larger input resolutions (e.g. stage 1,2), it is more efficient to use CNN-based layers to extract feature representations.

**Comment by jamesben6688** [comment]
Does this mean using CNN in the first two stages will lead to better  accuracy?
