### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by mtjhl** [NVlabs/FasterViT#2]
when I run `python onnx_convert.py`
there is bugs
```
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Given normalized_shape=[64, 1, 1], expected input with shape [*, 64, 1, 1], but got input of size[1, 64, 56, 56]
```
How to solve this problem?

**Comment by mtjhl** [comment]
Oh, timm version is too low, update timm will solve this problem.

**Comment by ahatamiz** [comment]
Hi @mtjhl , thanks for bringing up this issue. May I ask which version of the timm caused the issue ?
