### ISSUE TITLE
Object Detection with FasterViT-0 an 1

### ISSUE THREAD

**Issue by chuong98** [NVlabs/FasterViT#26]
Hi, thanks for releasing the code. Excellent paper, indeed.
I just wonder if you conducted experiments with object detection using smaller backbone, such as -0 and -1 size.
In the Table 3, I see that FasterViT-2 has almost +2mAP compared to SwinT, and speed x1.78.
It gives me the interpret that V0 and V1 can have almost equal mAP with Swin-T while can be 2.5x faster (based on Table 1).

Lastly, is the speed on Table 3 reported with TensorRT or Pytorch ?
Thank you.

**Comment by ahatamiz** [comment]
Hi @chuong98 thank you for the note. 

Regarding the first question, we did not try -0 and -1 variants, but I suppose conjecture should hold. 

The Table 3 results, and all other measurements in the main paper, are done in PyTorch. 

Best,

**Comment by ahatamiz** [comment]
Hi @chuong98 

Thank you for your inquiry and interest in object detection with FasterViT. 

We have released the FasterViT object detection [repository](https://github.com/NVlabs/FasterViT/tree/main/object_detection) with DINO. 

We will release pretrained checkpoint, which will include models with FasterViT-0 and 1 variants soon. 

I hope this can be useful.
