### ISSUE TITLE
same gamma parameter

### ISSUE THREAD

**Issue by OnderT** [NVlabs/FasterViT#35]
Hi, thanks for your nice work. I noticed that the same gamma parameter is used here https://github.com/NVlabs/FasterViT/blob/aa6eabef63e2ea547a957293772e75ecbde451c7/fastervit/models/faster_vit.py#L692 and here https://github.com/NVlabs/FasterViT/blob/aa6eabef63e2ea547a957293772e75ecbde451c7/fastervit/models/faster_vit.py#L713 . 

Is there any particular reason for this?
Thank you.

**Comment by ahatamiz** [comment]
Hi @OnderT, using a new layer-scale layer or sharing the same across multiple branches are both valid design choices. The latter can help with convergence and hence was selected. 

Best
