### ISSUE TITLE
confuse about use pretrained model to finetune on 1024 x 1024 images

### ISSUE THREAD

**Issue by dongshenhan** [NVlabs/FasterViT#43]
if i change image resolution like (1024,1024),can i also use pretrained model to finetune on my dataset ?

**Comment by ahatamiz** [comment]
@dongshenhan yes that's the purpose of providing this functionality. Given a strong pre-trained backbone on lower resolution (224x224), we want to enable usage for downstream tasks like detection/segmentation.
