### ISSUE TITLE
FSDP causes graph break in forward

### ISSUE THREAD

**Issue by Gutianpei** [NVlabs/FasterViT#51]
Hello,

I tried to use FSDP to accelerate the training, but get `graph break in forward` error in PosEmbMLPSwinv2D's `self.relative_bias = self.pos_emb` in forward function. However the error went away when I disabled torch.compile(). In my other projects torch.compile works well with FSDP so kind of curious what happened here. Any insight is highly appreciated. Thank you!

**Comment by ahatamiz** [comment]
Hi @Gutianpei 

Thanks for sharing these insights. We have not experimented with `model.compile`, but I suspect that the error is in isolation with regard to FSDP. My assumption is that there are unsupported kernels that cause this issue which need to be further investigated. 

Do you also get the same error with `model.compile` when not using FSDP ?

**Comment by Gutianpei** [comment]
Hello @ahatamiz 

Thanks for the reply. I agree with your guess, and there is no error when using torch.compile without FSDP. Another interesting thing is when I use SwinV2 with torch.compile and FSDP I didn't see any issue. Since the issue looks related more with FSDP/PyTorch than FasterViT itself feel free to close the issue.

**Comment by ahatamiz** [comment]
Thanks again @Gutianpei . I still have not gotten the time to fully investigate the interaction with torch.compile and FSDP. Both of these amazing contributions have been release after we started the work on FasterViT. But they should definitely be helpful.

For now I close this issue until I get to investigate. But also feel free to re-open or raise another issue if you have a new findings/insights/comments. I would be very interested to look into it.
