### ISSUE TITLE
Issue with faster_vit_4_224 checkpoint

### ISSUE THREAD

**Issue by numpee** [NVlabs/FasterViT#56]
Hi,
Interesting paper, and thanks for maintaining the repo :) 

There seems to be an issue with the `faster_vit_4_224` checkpoint, specifically. For example:

```python
from fastervit.models.faster_vit import faster_vit_4_224

model = faster_vit_4_224(pretrained=True)
```
will lead to the following size mismatch:
```
size mismatch for levels.2.blocks.0.attn.pos_emb_funct.relative_bias: copying a param with shape torch.Size([1, 16, 53, 53]) from checkpoint, the shape in current model is torch.Size([1, 8, 53, 53]).
size mismatch for levels.2.blocks.0.attn.pos_emb_funct.cpb_mlp.2.weight: copying a param with shape torch.Size([16, 512]) from checkpoint, the shape in current model is torch.Size([8, 512]).
size mismatch for levels.2.blocks.0.hat_attn.pos_emb_funct.relative_bias: copying a param with shape torch.Size([1, 16, 16, 16]) from checkpoint, the shape in current model is torch.Size([1, 8, 16, 16]).
size mismatch for levels.2.blocks.0.hat_attn.pos_emb_funct.cpb_mlp.2.weight: copying a param with shape torch.Size([16, 512]) from checkpoint, the shape in current model is torch.Size([8, 512]).
...
size mismatch for levels.3.blocks.4.attn.pos_emb_funct.cpb_mlp.2.weight: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([16, 512]).
```
Perhaps the number of heads was incorrect for levels 3 and 4?

I've checked `faster_vit_0~2` but they seem to be fine. **But, there is still a size mismatch when using `faster_vit_{0~6}_any_res` with resolution of `[224, 224]`**. Not sure why the size mismatch would occur when the resolution for `_any_res` is matched to the pretrain size.

**Comment by numpee** [comment]
Also, I'm curious if it is possible to use a different train and test resolution. For example, train on 1024x1024 then test on 1280 x 800 (common training and testing resolutions for COCO from Table 3). From what I can tell, using a different resolution (or aspect ratio) leads to the addition of new parameters, which would be randomly initialized, thereby causing issues in inference.

**Comment by ahatamiz** [comment]
Thank you so much @numpee for pointing out this issue. It is now addressed via #57. 

Regarding the second question, the any-resolution FasterViT allows for this functionality. Although you are right in the sense that new layers are could be added on the condition of input feature size being larger than window size. But it can be circumvented by simply adding another flag whether or not to run HAT. In this case, the former is overridden by the latter and hence no new layers would be added. 

I will try to add this soon, but it is quite trivial.

**Comment by ahatamiz** [comment]
Hi @numpee I opened up #59 to continue this conversation on the feature request. Hence, closing this issue for now. 

Thanks again for pointing out the problem !

**Comment by numpee** [comment]
Thanks for the quick fix (and response)!

I see, will look closer into that.

**Comment by ahatamiz** [comment]
Hi @numpee , we now have a [hat flag](https://github.com/NVlabs/FasterViT/blob/main/fastervit/models/faster_vit_any_res.py#L996) which allows you to control adoption of carrier tokens. In this case, if the model is trained on 224 x 224 resolution, the 4th stage does not originally have carrier token since `window_size==feature_size`. But upon using the model for higher resolution, this may not be the case. Hence this flag allow to override creating new layers on the basis of this condition. 

I hope this is useful.

**Comment by numpee** [comment]
I see, thanks for the update. Did you use this functionality when using FasterViT as the backbone for instance seg/detection experiments?

**Comment by ahatamiz** [comment]
Yes, we did use this to avoid creation of new layers.
