### ISSUE TITLE
Wrong shape order in TokenInitailizer?

### ISSUE THREAD

**Issue by Birdylx** [NVlabs/FasterViT#6]
@ahatamiz  Hi, thanks for you work, but it seems the shape over [here](https://github.com/NVlabs/FasterViT/blob/8ffeadd353911a3da3d91894cbf43f0761dbe29d/models/faster_vit_any_res.py#L761) is in wrong order?

**Comment by ahatamiz** [comment]
Hi @Birdylx thank you for your meticulous attention to the details :+1: 

#8 should address this issue.

**Comment by Birdylx** [comment]
@ahatamiz, I wonder if you're using square image to train objection and segmentation model, if not, seems this wrong tokenization doesn't hurt performance.

**Comment by ahatamiz** [comment]
Thanks again @Birdylx for the feedback. Fortunately, this only happened during refactoring for the newly added `faster_vit_any_res` model and did not impact any of the experiments. And also as indicated in the paper, experiments are done on non-square image size for segmentation, detection. 

I also agree with you about the performance. It should not still impact the performance, but we also made sure that shape order is correct in `TokenInitializer`.
