### ISSUE TITLE
Bug in fastervit package: faster_vit_2_any_res

### ISSUE THREAD

**Issue by luke-mcdermott-mi** [NVlabs/FasterViT#72]
Downloaded FasterViT with "pip install fastervit" today (July 25th), getting error when using faster_vit_2_any_res

```
model = FasterViT(depths=depths,
...
   1073                   drop_path_rate=drop_path_rate,
-> 1074                   hat=hat
   1075                   **kwargs)
   1076 model.default_cfg = default_cfgs['faster_vit_2_any_res']
   1077 if pretrained:

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'dict'
```

It appears theres no comma after hat parameter in faster_vit_2_any_res. There does exist a comma in the github repo though.

**Comment by ahatamiz** [comment]
@luke-mcdermott-mi sorry about this issue. Please kindly update the pip package to `fastervit==0.9.4` as the issue should be resolved.
