### ISSUE TITLE
About model profiling.

### ISSUE THREAD

**Issue by TsingWei** [NVlabs/FasterViT#75]
Hello,

I'm intrigued by the NVIDIA DLSIM profiling tool as mentioned in Appendix H of the paper. My searches on Google haven't yielded much information about it. Could you please provide guidance on how to use it for profiling my model?

Thank you in advance.

**Comment by ahatamiz** [comment]
Hi @TsingWei , thanks for the comment. DLSIM is currently an internal tool for profiling the DL training and inference. I am not aware of any open-source version, but we used it to understand the impact of different operations, kernels, etc. using different NVIDIA hardware. And as shown in the figure you mentioned, HAT takes the majority of memory/latency footprint in the entire network, which indicates its critical role.

**Comment by falcon-xu** [comment]
Hello, it's a wonderful work. 

Could you please introduce some open-source tools to profile latency, memeory, FLOPs?

Thanks a lot.
