### ISSUE TITLE
confusion about ct_dewindow 

### ISSUE THREAD

**Issue by becauseofAI** [NVlabs/FasterViT#79]
The dimensions of  init ct and curent ct are different when ct_dewindow. How to solve it when mulit-scale training?

**Comment by ahatamiz** [comment]
Hi @becauseofAI, it would be great if you can share more details. It is possible to attain a single-resolution init_ct if needed. The size of the carrier tokens are dynamically computed based on use specifications in the [TokenInitializer](https://github.com/NVlabs/FasterViT/blob/main/fastervit/models/faster_vit_any_res.py#L693). Hence it can be adjusted to avoid shape mismatch.

**Comment by ahatamiz** [comment]
Thanks again @becauseofAI for your interest in FasterViT and object detection code. 

We can still use FasterViT for [object detection](https://github.com/NVlabs/FasterViT/tree/main/object_detection) with multi-scale training. The [ct_dewindow](https://github.com/NVlabs/FasterViT/blob/main/object_detection/models/dino/fastervit.py#L34) does not create any bottleneck.
