### ISSUE TITLE
Cross- attention

### ISSUE THREAD

**Issue by williamhoole** [NVlabs/FasterViT#98]

**Comment by ahatamiz** [comment]
Hi @williamhoole , thanks for bringing this application to our attention. 

I would be interested to know about it. Please point me to the paper and repository. 

Also PRs are always welcome, if you want to add this new application to FasterViT repository.

**Comment by williamhoole** [comment]
The implementation we are currently using is called Unimatch, which is a unified model for three motion and 3D perception tasks ( we mainly use it for disparity). You can find their repository [here](https://github.com/autonomousvision/unimatch) and their paper [here](https://arxiv.org/abs/2211.05783). It is a very interesting implimentation and personally we have tested unimatch which has shown good results! However we are looking at improving this model to achieve greater accuracy and especially faster inference speeds for edge devices such as a Jetson.

**Comment by ahatamiz** [comment]
Thank you @williamhoole for sharing this work. I will look into it.
